name: Azure Web App Deploy

env:
  AZURE_WEBAPP_NAME: app-prezentex-test  

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build /server/Prezentex.Api/Prezentex.Api.csproj --configuration Debug

    - name: Publish with dotnet
      run: dotnet publish /server/Prezentex.Api/Prezentex.Api.csproj --configuration Debug --output publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: ${{ secrets.AZURE_SLOT_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
