name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore **/Prezentex.Test
    - name: Build
      run: dotnet build **/Prezentex.Test --no-restore
    - name: Test
      run: dotnet test **/Prezentex.Test --no-build --verbosity normal
